## PheWAS results

library(tidyverse)
library(ggh4x)

premat_phen <- rio::import("~/dva/files/premat_phen.tsv")

dx_groups <- list(
    Anthropometric = c("Obesity",
                       "Weight",
                       "Childhood obesity",
                       "Hip circumference",
                       "Waist circumference",
                       "Waist-to-hip ratio",
                       "Extreme waist-to-hip ratio",
                       "Obesity class 1",
                       "Overweight",
                       "Body mass index",
                       "body mass index",
                       "Comparative body size at age 10",
                       "Leg fat-free mass (right)",
                       "Whole body fat-free mass",
                       "Impedance of leg (left)",
                       "Leg predicted mass (right)",
                       "Whole body water mass",
                       "Diagnoses - secondary ICD10: E66.9 Obesity, unspecified",
                       "Leg fat-free mass (left)",
                       "Arm fat mass (left)",
                       "Arm predicted mass (right)",
                       "Leg predicted mass (left)",
                       "Impedance of arm (right)",
                       "Trunk fat-free mass",
                       "Leg fat mass (right)",
                       "Impedance of arm (left)",
                       "Arm fat-free mass (right)",
                       "Impedance of whole body",
                       "Arm fat-free mass (left)",
                       "Body mass index (BMI)",
                       "Arm fat mass (right)",
                       "Leg fat mass (left)",
                       "Arm predicted mass (left)",
                       "Trunk predicted mass",
                       "Impedance of leg (right)",
                       "Weight change during worst episode of depression: Lost weight"),
    Mortality = c("Parental longevity (father's age at death)",
                  "Father's age"),
    Endocrine_Metabolic = c("Modified Stumvoll Insulin Sensitivity Index (model adjusted for BMI)",
                            "Modified Stumvoll Insulin Sensitivity Index",
                            "Homeostasis model assessment of insulin resistance",
                            "Adiponectin",
                            "apolipoprotein A-I",
                            "HDL cholesterol",
                            "HOMA-IR",
                            "Basal metabolic rate",
                            "Apoliprotein A",
                            "SHBG",
                            "Endocrine, nutritional and metabolic diseases"),
    Gastrointestinal = c("Non-cancer illness code  self-reported: cholelithiasis/gall stones",
                         "Diagnoses - main ICD10: K76 Other diseases of liver",
                         "Medication for pain relief, constipation, heartburn: Omeprazole (e.g. Zanprol)",
                         "Total protein",
                         "Ulcer of oesophagus",
                         "Alanine aminotransferase",
                         "Aspartate aminotransferase",
                         "Gamma glutamyltransferase",
                         "Diagnoses - main ICD10: N39.3 Stress incontinence",
                         "Treatment/medication code: omeprazole",
                         "Diagnoses - secondary ICD10: K44.9 Diaphragmatic hernia without obstruction or gangrene",
                         "Operative procedures - main OPCS: T20.2 Primary repair of inguinal hernia using insert of prosthetic material"),
    Ophtalmological = c("Treatment speciality of consultant (recoded): Ophthalmology",
                        "Eye problems/disorders: None of the above",
                        "Operative procedures - secondary OPCS: C71.2 Phacoemulsification of lens",
                        "Other eye problems",
                        "Which eye(s) affected by astigmatism: Right eye",
                        "Main speciality of consultant (recoded): Ophthalmology"),
    Haematologic = c("Red blood cell count",
                     "Urate",
                     "CD27 on CD24+ CD27+ B cell",
                     "CD27 on IgD- CD38- B cell",
                     "CD27 on IgD- CD38dim B cell",
                     "CD27 on switched memory B cell",
                     "C-Reactive protein level",
                     "White blood cell (leukocyte) count",
                     "Red blood cell (erythrocyte) count",
                     "Mean corpuscular volume",
                     "Reticulocyte percentage",
                     "Reticulocyte count",
                     "Mean sphered cell volume",
                     "High light scatter reticulocyte percentage",
                     "High light scatter reticulocyte count"),
    Cardiovascular = c("Coronary artery disease",
                       "Treatment/medication code: amlodipine",
                       "Illnesses of siblings: Stroke",
                       "Illnesses of mother: Stroke",
                       "Chest pain or discomfort when walking uphill or hurrying",
                       "Stroke",
                       "Systolic blood pressure, automated reading",
                       "Ischemic stroke",
                       "Ischemic stroke (small-vessel)",
                       "Heart failure",
                       "Operation code: coronary angioplasty (ptca) +/- stent",
                       "Myocardial fractal dimension (slice 2)",
                       "Coronary heart disease",
                       "systolic blood pressure",
                       "diastolic blood pressure",
                       "Treatment/medication code: doxazosin",
                       "Vascular/heart problems diagnosed by doctor: Stroke",
                       "Treatment/medication code: enalapril",
                       "Treatment/medication code: clopidogrel",
                       "Systolic blood pressure  automated reading",
                       "Main speciality of consultant (recoded): Cardiothoracic surgery",
                       "Treatment/medication code: losartan",
                       "Treatment/medication code: ramipril",
                       "Treatment/medication code: lisinopril",
                       "Treatment/medication code: candesartan cilexetil",
                       "Treatment/medication code: perindopril",
                       "Cardiac arrhytmias, COPD co-morbidities",
                       "Diagnoses - main ICD10: I50 Heart failure",
                       "Heart failure,strict",
                       "Heart failure, not strict",
                       "Operative procedures - main OPCS: K63.4 Coronary arteriography using two catheters"),
    Musculoskeletal = c("Total body bone mineral density",
                        "Total body bone mineral density (age over 60)",
                        "Heel bone mineral density",
                        "Heel bone mineral density (BMD)",
                        "Heel broadband ultrasound attenuation (right)",
                        "Heel bone mineral density (BMD) T-score, automated (right)",
                        "Heel bone mineral density (BMD) T-score, automated",
                        "Heel bone ultrasound T-score, manual entry",
                        "Operation code: carpal tunnel surgery",
                        "Heel Broadband ultrasound attenuation (BUA), manual entry",
                        "Treatment/medication code: alendronate sodium",
                        "Femoral neck bone mineral density",
                        "Heel bone mineral density (BMD) (right)",
                        "Heel quantitative ultrasound index (QUI), direct entry (right)",
                        "Lumbar spine bone mineral density",
                        "Heel quantitative ultrasound index (QUI), direct entry (left)",
                        "Heel bone mineral density (BMD) T-score  automated (left)",
                        "Heel bone mineral density (BMD) T-score  automated (right)",
                        "Disorders of synovium and tendon",
                        "Diagnoses - main ICD10: G56 Mononeuropathies of upper limb",
                        "Non-cancer illness code  self-reported: osteoporosis",
                        "Heel bone mineral density (BMD) (left)",
                        "Heel bone mineral density (BMD), manual entry",
                        "Heel bone mineral density (BMD) T-score, automated (left)",
                        "Heel quantitative ultrasound index (QUI), direct entry"),
    Obstetric_Gynecologic = c("Endometrial cancer",
                              "Malignant neoplasm of corpus uteri",
                              "Endometrial cancer (endometrioid histology)",
                              "Age when periods started (menarche)",
                              "Diagnoses - main ICD10: N81 Female genital prolapse",
                              "Operation code: caesarean section / caesarian section",
                              "Operative procedures - secondary OPCS: Q22.1 Bilateral salpingoophorectomy"),
    Respiratory = c("Lung function (FVC)",
                    "Childhood asthma (age<16)",
                    "Asthma, hospital admissions 1",
                    "Asthma",
                    "Diagnoses - main ICD10: J45 Asthma"),
    Neurological_Psychiatric = c("Intracranial volume",
                                 "Prospective memory result",
                                 "Ever manic/hyper for 2 days",
                                 "Diseases of the nervous system",
                                 "Illness, injury, bereavement, stress in last 2 years: Serious illness, injury or assault to yourself",
                                 "Ever worried more than most people would in similar situation",
                                 "Sleeping too much",
                                 "Final attempt correct: yes",
                                 "FI9 : concept interpolation",
                                 "Nerve, nerve root and plexus disorders"),
    Infectious = c("Treatment/medication code: quinine",
                   "Diagnoses - main ICD10: L02 Cutaneous abscess, furuncle and carbuncle"),
    Lifestyle = c("Exposure to tobacco smoke at home",
                  "Alcohol drinker status: Previous",
                  "Transport type for commuting to job workplace: Walk",
                  "Pack years adult smoking as proportion of life span exposed to smoking PREVIEW ONLY",
                  "Why stopped smoking: Health precaution",
                  "Types of physical activity in last 4 weeks: Strenuous sports",
                  "Alcohol intake frequency.",
                  "Milk type used: Semi-skimmed",
                  "Alcohol drinker status: Current",
                  "Average weekly fortified wine intake",
                  "Alcohol intake versus 10 years previously",
                  "Types of physical activity in last 4 weeks: Heavy DIY (eg: weeding  lawn mowing  carpentry  digging)",
                  "Job involves shift work",
                  "Vitamin and mineral supplements: Vitamin D",
                  "Home location - east co-ordinate (rounded)",
                  "Reason for reducing amount of alcohol drunk: Doctor's advice",
                  "Types of physical activity in last 4 weeks: Heavy DIY (eg: weeding, lawn mowing, carpentry, digging)",
                  "Own or rent accommodation lived in: Rent - from local authority, local council, housing association",
                  "Never eat eggs, dairy, wheat, sugar: Wheat products"),
    `General health` = c("Number of self-reported non-cancer illnesses",
                         "Number of treatments/medications taken",
                         "Diagnoses - secondary ICD10: Z92.2 Personal history of long-term (current) use of other medicaments",
                         "Interpolated Age of participant when non-cancer illness first diagnosed",
                         "Methods of admission to hospital (recoded): Emergency admission: GP",
                         "Diagnoses - main ICD10: R69 Unknown and unspecified causes of morbidity",
                         "Intended management of patient (recoded): One or more nights hospital stay",
                         "Operative procedures - secondary OPCS: Y82.9 Unspecified local anaesthetic",
                         "Operative procedures - main OPCS: X99.8 No procedure performed",
                         "Attendance/disability/mobility allowance: Disability living allowance",
                         "Interpolated Year when operation took place")
)

dxtab <- dx_groups %>%
    map_dfr(~data.frame(trait = .x, n = length(.x)), .id = "dxgrp")

dxtab_c <- premat_phen %>%
    select(trait, p_comp, p_comp_adj) %>%
    unique %>%
    left_join(dxtab)

phewas_res <- dxtab_c %>%
    mutate(p_comp = -log10(p_comp),
           p_comp = ifelse(p_comp > 10, 10, p_comp),
           dxgrp = str_replace_all(dxgrp, "_", "/")) %>%
    ggplot(aes(weave_factors(reorder(dxgrp, desc(n)),
                             reorder(trait, desc(p_comp))), p_comp)) +
    geom_point(aes(color = reorder(dxgrp, desc(n)))) +
    labs(x = "Traits", y = "-log10 p", color = "Trait groups") +
    theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank())

save(phewas_res, file = "../plot_files/phewas_res.RData")

ggsave("../docs/plots/phewas_res.png", phewas_res)
